### ISSUE TITLE
建議用「tag 標籤」來取代「關鍵字」一詞；標籤靈感共筆、標籤翻譯工作

### ISSUE THREAD

**Issue by cheweiliu** [g0v/aray#28]
建議用「tag 標籤」來取代「關鍵字」一詞

請搭配 #29 建議用「category 影響力類別」來取代「標籤管理」 
共同評估

---
[標籤靈感共筆文件link](https://g0v.hackmd.io/oo2o9M_TTLaVHudGPfCH1g?view)

---
開始開放標記之後，是否有需要處理 標籤翻譯
將既有中文標籤建立英文字詞
或是將既有英文標籤翻成中文
用於 EN 情境

**Comment by chunyenHuang** [comment]
已更新囉
標籤的內容會由使用者自訂，翻譯部分我開了另外一個issue
