### ISSUE TITLE
建議用「category 影響力類別」來取代「標籤管理」用詞

### ISSUE THREAD

**Issue by cheweiliu** [g0v/aray#29]
看起來這部分是比較屬於有一套分類架構，或許用詞上更適合「影響力類別、議題分類」等用詞

英文：category
中文：影響力類別、議題分類 .. 等用詞
擴充方案：待確認，例如 2020 出現的「防疫」，如果重要程度已提升至「影響力類別」，那麼要如何提出、確認

若採用上述方案，就可以讓「標籤」一詞，用於較為彈性的標註

英文：tag
中文：標籤
擴充方案：使用者可自行新增，僅在違反 CoC 的時候進行管理

請搭配 #28 建議用「keyword 標籤」來取代「關鍵字」一詞
共同評估

**Comment by chunyenHuang** [comment]
我覺得滿合理的 我近期找時間改一下

**Comment by chunyenHuang** [comment]
更新囉～感謝你的建議
